#!/bin/bash

echo "🛠️ Generating full Palworld pals list..."

mkdir -p src/data

node <<'EOF'
const fs = require("fs");

// Full list of Palworld Pals (137 entries)
const pals = [
  {"id":"001","name":"Lamball"},
  {"id":"002","name":"Cattiva"},
  {"id":"003","name":"Chikipi"},
  {"id":"004","name":"Lifmunk"},
  {"id":"005","name":"Foxparks"},
  {"id":"006","name":"Fuack"},
  {"id":"007","name":"Sparkit"},
  {"id":"008","name":"Tanzee"},
  {"id":"009","name":"Rooby"},
  {"id":"010","name":"Pengullet"},
  {"id":"011","name":"Penking"},
  {"id":"012","name":"Jolthog"},
  {"id":"012B","name":"Jolthog Cryst"},
  {"id":"013","name":"Gumoss"},
  {"id":"014","name":"Vixy"},
  {"id":"015","name":"Hoocrates"},
  {"id":"016","name":"Teafant"},
  {"id":"017","name":"Depresso"},
  {"id":"018","name":"Cremis"},
  {"id":"019","name":"Daedream"},
  {"id":"020","name":"Rushoar"},
  {"id":"021","name":"Nitewing"},
  {"id":"022","name":"Fuddler"},
  {"id":"023","name":"Killamari"},
  {"id":"024","name":"Mau"},
  {"id":"024B","name":"Mau Cryst"},
  {"id":"025","name":"Celaray"},
  {"id":"026","name":"Direhowl"},
  {"id":"027","name":"Tocotoco"},
  {"id":"028","name":"Flopie"},
  {"id":"029","name":"Mozzarina"},
  {"id":"030","name":"Bristla"},
  {"id":"031","name":"Gobfin"},
  {"id":"031B","name":"Gobfin Ignis"},
  {"id":"032","name":"Hangyu"},
  {"id":"032B","name":"Hangyu Cryst"},
  {"id":"033","name":"Mossanda"},
  {"id":"033B","name":"Mossanda Lux"},
  {"id":"034","name":"Woolipop"},
  {"id":"035","name":"Caprity"},
  {"id":"036","name":"Melpaca"},
  {"id":"037","name":"Eikthyrdeer"},
  {"id":"037B","name":"Eikthyrdeer Terra"},
  {"id":"038","name":"Nitewing"},
  {"id":"039","name":"Ribunny"},
  {"id":"040","name":"Incineram"},
  {"id":"040B","name":"Incineram Noct"},
  {"id":"041","name":"Cinnamoth"},
  {"id":"042","name":"Arsox"},
  {"id":"043","name":"Dumud"},
  {"id":"044","name":"Cawgnito"},
  {"id":"045","name":"Leezpunk"},
  {"id":"045B","name":"Leezpunk Ignis"},
  {"id":"046","name":"Loupmoon"},
  {"id":"047","name":"Galeclaw"},
  {"id":"048","name":"Robinquill"},
  {"id":"048B","name":"Robinquill Terra"},
  {"id":"049","name":"Gorirat"},
  {"id":"049B","name":"Gorirat Terra"},
  {"id":"050","name":"Beegarde"},
  {"id":"051","name":"Elizabee"},
  {"id":"052","name":"Grintale"},
  {"id":"053","name":"Swee"},
  {"id":"054","name":"Sweepa"},
  {"id":"055","name":"Chillet"},
  {"id":"056","name":"Univolt"},
  {"id":"057","name":"Foxcicle"},
  {"id":"058","name":"Pyrin"},
  {"id":"058B","name":"Pyrin Noct"},
  {"id":"059","name":"Reindrix"},
  {"id":"060","name":"Rayhound"},
  {"id":"061","name":"Kitsun"},
  {"id":"062","name":"Dazzi"},
  {"id":"063","name":"Lunaris"},
  {"id":"064","name":"Dinossom"},
  {"id":"064B","name":"Dinossom Lux"},
  {"id":"065","name":"Surfent"},
  {"id":"065B","name":"Surfent Terra"},
  {"id":"066","name":"Maraith"},
  {"id":"067","name":"Digtoise"},
  {"id":"068","name":"Tombat"},
  {"id":"069","name":"Lovander"},
  {"id":"070","name":"Flambelle"},
  {"id":"071","name":"Vanwyrm"},
  {"id":"071B","name":"Vanwyrm Cryst"},
  {"id":"072","name":"Bushi"},
  {"id":"073","name":"Beakon"},
  {"id":"074","name":"Ragnahawk"},
  {"id":"075","name":"Katress"},
  {"id":"076","name":"Wixen"},
  {"id":"077","name":"Verdash"},
  {"id":"078","name":"Vaelet"},
  {"id":"079","name":"Sibelyx"},
  {"id":"080","name":"Elphidran"},
  {"id":"080B","name":"Elphidran Aqua"},
  {"id":"081","name":"Kelpsea"},
  {"id":"081B","name":"Kelpsea Ignis"},
  {"id":"082","name":"Azurobe"},
  {"id":"083","name":"Cryolinx"},
  {"id":"084","name":"Blazehowl"},
  {"id":"084B","name":"Blazehowl Noct"},
  {"id":"085","name":"Relaxaurus"},
  {"id":"085B","name":"Relaxaurus Lux"},
  {"id":"086","name":"Broncherry"},
  {"id":"086B","name":"Broncherry Aqua"},
  {"id":"087","name":"Petallia"},
  {"id":"088","name":"Reptyro"},
  {"id":"088B","name":"Reptyro Cryst"},
  {"id":"089","name":"Kingpaca"},
  {"id":"089B","name":"Kingpaca Cryst"},
  {"id":"090","name":"Mammorest"},
  {"id":"090B","name":"Mammorest Cryst"},
  {"id":"091","name":"Wumpo"},
  {"id":"091B","name":"Wumpo Botan"},
  {"id":"092","name":"Warsect"},
  {"id":"093","name":"Fenglope"},
  {"id":"094","name":"Felbat"},
  {"id":"095","name":"Quivern"},
  {"id":"096","name":"Blazamut"},
  {"id":"097","name":"Helzephyr"},
  {"id":"098","name":"Astegon"},
  {"id":"099","name":"Menasting"},
  {"id":"100","name":"Anubis"},
  {"id":"101","name":"Jormuntide"},
  {"id":"101B","name":"Jormuntide Ignis"},
  {"id":"102","name":"Suzaku"},
  {"id":"102B","name":"Suzaku Aqua"},
  {"id":"103","name":"Grizzbolt"},
  {"id":"104","name":"Lyleen"},
  {"id":"104B","name":"Lyleen Noct"},
  {"id":"105","name":"Faleris"},
  {"id":"106","name":"Orserk"},
  {"id":"107","name":"Shadowbeak"},
  {"id":"108","name":"Paladius"},
  {"id":"109","name":"Necromus"},
  {"id":"110","name":"Frostallion"},
  {"id":"110B","name":"Frostallion Noct"},
  {"id":"111","name":"Jetragon"}
];

const withImages = pals.map(p => ({
  id: p.id,
  name: p.name,
  imageUrl: `https://palworld.gg/static/pal_icon/${p.name.toLowerCase().replace(/[^a-z0-9]+/g,"_")}.png`
}));

fs.writeFileSync("src/data/pals.json", JSON.stringify(withImages, null,2));
console.log("✅ Generated full pals.json (" + withImages.length + " pals).");
EOF
